---
title: "Data wrangling_Berkeley dataset"
author: "Jadyn Park"
date: '2022-06-07'
output: html_document
---

```{r setup, include=FALSE}

## clear environment
rm(list = ls())

## load libraries
library(tidyverse); library(dplyr); library(readr); library(purrr)

## set working directory
setwd("~/Desktop/Uchicago/MotPupil/")

LC_1001 <- read.csv("~/Desktop/Uchicago/MotPupil/1001.csv")
LC_1002 <- read.csv("~/Desktop/Uchicago/MotPupil/1002.csv")
LC_1003 <- read.csv("~/Desktop/Uchicago/MotPupil/1003.csv")
LC_1004 <- read.csv("~/Desktop/Uchicago/MotPupil/1004.csv")
LC_1005 <- read.csv("~/Desktop/Uchicago/MotPupil/1005.csv")
LC_1006 <- read.csv("~/Desktop/Uchicago/MotPupil/1006.csv")
LC_1007 <- read.csv("~/Desktop/Uchicago/MotPupil/1007.csv")
LC_1008 <- read.csv("~/Desktop/Uchicago/MotPupil/1008.csv")

LC_1001$subj_idx <- "1001"
LC_1002$subj_idx <- "1002"
LC_1003$subj_idx <- "1003"
LC_1004$subj_idx <- "1004"
LC_1005$subj_idx <- "1005"
LC_1006$subj_idx <- "1006"
LC_1007$subj_idx <- "1007"
LC_1008$subj_idx <- "1008"

raw.list <- do.call("rbind", list(LC_1001, LC_1002, LC_1003, LC_1004, LC_1005, LC_1006, LC_1007, LC_1008))
raw <- as.data.frame(raw.list)
```

```{r echo=T}
## add subject number
df <- raw

## sort rows by trial_order
df <- df %>% arrange(subj_idx, trial_order)

## remove rows where rt is NA
df <- df %>% drop_na(rt)

## select relevant columns
df <- df %>% select(subj_idx, scene_proportion, choice, rt, Mot_type)

## mutate scene_proportion as stim, such that 0.33 = -1.5; 0.43 = -0.5; 0.48 = 0; 0.53 = 0.5; 0.63 = 1.5
df <- df %>% mutate(stim = factor(scene_proportion, levels=c(.33, .43, .48, .53, .63),
                                  labels=c(-1.5, -.5, 0, .5, 1.5)))
  
  
## mutate choice as response such that Face = 0, Scene = 1
df <- df %>% mutate(response = factor(choice, levels=c("Scene", "Face"),
                                      labels=c(1, 0)))

## mutate Mot_type as condition such that Scene = 1, Face = -1, No = 0
df <- df %>% mutate(condition = factor(Mot_type, levels=c("Scene", "Face", "No"),
                                      labels=c(1, -1, 0)))

## select final variables
df <- df %>% select(subj_idx, stim, response, rt, condition)

## add MotCon column
df$MotCon <- ifelse(df$condition==1 & df$response==0 | df$condition==-1 & df$response==1, -1,
                    ifelse(df$condition==1 & df$response==1 | df$condition==-1 & df$response==0, 1, 0))

  # if condition = scene (1) & response = 0 -> MotCon = -1
  # if condition = scene (1) & response = 1 -> MotCon = 1
  # if condition = neutral (0) & response = 0 -> MotCon = 0
  # if condition = neutral (0) & response = 1 -> MotCon = 0
  # if condition = face (-1) & response = 0 -> MotCon = 1
  # if condition = face (-1) & response = 1 -> MotCon = -1

write.csv(df, "~/Desktop/Uchicago/MotPupil/Berkeley_data_cleaned.csv")

## exclude subject 1008
df_1007 <- df %>% filter(subj_idx!="1008")
write.csv(df_1007, "~/Desktop/Uchicago/MotPupil/Berkeley_data_1001-1007.csv")
```